### PR TITLE
forward an backward subcommands to seek current track

### PR DESCRIPTION
**Pull request by sudaraka**
Examples:

- `playerctl forward 60` fast-forward 60 seconds
- `playerctl backward 60` rewind 60 seconds

### CODE REVIEW

**Comment by acrisci** [comment]
Reference:

http://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Method:Seek

We can also set position:

http://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Method:SetPosition

What do you think about combining all of these into one command? Something like `playerctl position [where][+|-]` where if + or - is given, it will seek and otherwise it will go to the absolute position given in seconds? It would also make this functionality consistent with volume setting.

**Comment by sudaraka** [comment]
That makes sense. I will work on that when I get a chance.

**Comment by sudaraka** [comment]
Well, it took me sometime to look into this. I got the `position N+/-` working, but could not figure out how to set exact position with `position N`. Hope someone can shed some light on that.

**Comment by acrisci** [comment]
I am going to merge this and then change it to support setting exact position since I have some time this weekend. I might need to change the library interface somewhat to do it though.

Thanks for the contribution :+1:

**Comment by acrisci** [comment]
Ok I made the changes that allow it to go to a specific position. Please test.

**Comment by sudaraka** [comment]
Everything I used it for is working perfectly.

Thanks!

**Pull request merged**
